// react-app/src/hello/Hello.jsx
import React from 'react';

class Hello extends React.Component {
  onClick = (e) => {
    console.log(e);
    this.props.onHello({ message: 'Hello React!' });
  }

  render() {
    return (
    <div>
      <p >Hello React!</p>
      <button  onClick={this.onClick}>HELLO</button>
    </div>
    )
  }
}

export default Hello

// vue-app/src/components/Hello.vue
<template>
  <p>Hello Vue!</p>
  <button @click="onClick">HELLO</button>
</template>

<script>
export default {
  name: 'Hello',
  emits: ['hello'],
  methods: {
    onClick(event) {
      console.log(event);
      this.$emit('hello', { message: 'hello Vue!' })
    }
  },
  mounted() {
    console.log(this);
  }
}
</script>
