// svelte-app/src/components/Hello.svelte
<script>
  import { createEventDispatcher, onMount } from "svelte";
  const dispatch = createEventDispatcher();

  onMount(() => console.log(this));

  function onClick(e) {
    dispatch("hello", { message: "Hello Svelte!" });
  }
</script>

<p>Hello Svelte!</p>
<button on:click={onClick}>HELLO</button>

// react-app/src/hello/Hello.jsx
import React from 'react';

class Hello extends React.Component {
  onClick = (e) => {
    console.log(e);
    this.props.onHello({ message: 'Hello React!' });
  }

  render() {
    return (
    <div>
      <p >Hello React!</p>
      <button  onClick={this.onClick}>HELLO</button>
    </div>
    )
  }
}

export default Hello
