// vue-app/src/components/Hello.vue
<template>
  <p>Hello Vue!</p>
  <button @click="onClick">HELLO</button>
</template>

<script>
export default {
  name: 'Hello',
  emits: ['hello'],
  methods: {
    onClick(event) {
      console.log(event);
      this.$emit('hello', { message: 'hello Vue!' })
    }
  },
  mounted() {
    console.log(this);
  }
}
</script>

// angular-app/src/app/hello/hello.component.ts
import { Component, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-hello',
  templateUrl: './hello.component.html'
})
export class HelloComponent {
  @Output() hello = new EventEmitter<{ message: string }>();

  constructor() { }

  onClick(e: Event) {
    console.log(e);
    this.hello.emit({ message: 'Hello Angular!' });
  }
}

<p>Hello Angular!</p>
<button (click)="onClick($event)">HELLO</button>
